name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  linux:
    name: go-linux
    strategy:
      matrix:
        go: ["1.20", "1.21", "1.22"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"

      - run: go test ./...

  linux-32bit:
    name: go-linux-32bit
    strategy:
      matrix:
        go: ["1.20", "1.21", "1.22"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"

      - run: go test ./...

  darwin:
    name: go-macos
    strategy:
      matrix:
        go: ["1.20", "1.21", "1.22"]
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"

      - run: go test ./...

  linux-stress:
    name: go-linux-stress
    strategy:
      matrix:
        go: ["1.20", "1.21", "1.22"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"

      - run: go test ./... -exec 'stress -p 4 -maxruns 1000' -v

  linux-stress-race:
    name: go-linux-stress-race
    strategy:
      matrix:
        go: ["1.20", "1.21", "1.22"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"

      - run: go test ./... -race -exec 'stress -p 2 -maxruns 100' -v
